apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: registryx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:15-alpine
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres-svc -U registryx; do echo waiting for db; sleep 2; done;",
            ]
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: registryx-secrets
                  key: DB_PASSWORD
      containers:
        - name: backend
          # You'll need to push your image to a real registry (e.g. dockerhub or GHCR)
          image: ckmine11/registryx-backend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: registryx-config
            - secretRef:
                name: registryx-secrets
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: registryx-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: registryx-secrets
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 5000
          # Mount docker socket for Trivy? Or assume Trivy is embedded?
          # Current logic runs 'trivy' binary inside the container.
          # So we need to ensure the image has 'trivy' installed.
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: registryx
spec:
  type: LoadBalancer # Or ClusterIP if using Ingress
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: backend
